### ISSUE TITLE
Can't make it work

### ISSUE THREAD

**Issue by Dagsbio** [bioliyezhang/PTI#1]
Hi, I'm trying to use the tool but there's no way I can make it work, not even trying with your example files.

Could you provide a specific example with a clear input and output?

Best,

David.

**Comment by Bio-wupin** [comment]
> 
Hi David,

Thanks for your question. If you want to run PTI, you need to install package "biopython" first. I'm sorry we didn't mention this in the manual. We suspect that this potential techinical issue caused the problem. 

If you have not installed "biopython" in advance, you will receive an error "ModuleNotFoundError: No module named 'Bio'".

When running PTI, if your input data is a Binary matrix, such as "Demo/Test1/Test1.txt", you can use the command:
>>python PTI-v1.0/PTI.py -i Demo/Test1/ -o ./
#The folder path of the input file: Demo/Test1/   
#output files: Test1_info_0.txt   &    Test1_tree_0.pdf

If your input data is "One sample per file", such as "Demo/Test2/*", you can run
>>python PTI-v1.0/PTI.py --AF 0 -i Demo/Test2/ -o ./
#input: Demo/Test2/   
#AF: User-defined parameter
#output files: Test2_info_0.txt   &    Test2_tree_0.pdf

Please try running PTI again and feel free to ask if you have any questions.

##Intermediate information output when running PTI
AF: 
file_path: Demo/Test1
file_path_out: .
driver_gene_path: /hpc/data/home/slst/zhangly/wupin/share/PTI/PTI-v1.0
['Test1.txt']
0-1 matrix
patient: Test1
['R2', 'LN1a', 'LN1b', 'R1', 'R3', 'R7', 'R4', 'R15', 'R6']
R2 have mutations: 60
LN1a have mutations: 57
LN1b have mutations: 57
R1 have mutations: 59
R3 have mutations: 58
R7 have mutations: 64
R4 have mutations: 59
R15 have mutations: 60
R6 have mutations: 58
every gene refer to a uniq gene
branch_path count: 5
path_string: 5
all_result: 5
DIC_result: 5
tree_structure:
(R6:3[1-SPOP],((LN1a:0[0],LN1b:0[0]):1[0],R2:4[0]):1[0],((R1:1[0],R3:0[0],R4:1[0],R7:6[0]):1[0],R15:3[1-MACF1]):2[0]):55[2-ASXL2;VHL]
Test1 ok!

**Comment by Dagsbio** [comment]
Solved, thank you!
