### ISSUE TITLE
Binary matrix working, but I can't make the "one sample per file" version to work

### ISSUE THREAD

**Issue by Dagsbio** [bioliyezhang/PTI#2]
Hi again,

I am having now issues running this: 

![image](https://user-images.githubusercontent.com/23311037/211837584-f75b763c-a952-486d-bb9b-1010ebea49b8.png)

Files look like this:

![image](https://user-images.githubusercontent.com/23311037/211837832-23b218b1-05ba-449a-9b29-3888adcbec30.png)

**Comment by Bio-wupin** [comment]
> Hi again,
> 
> I am having now issues running this:
> 
> ![image](https://user-images.githubusercontent.com/23311037/211837584-f75b763c-a952-486d-bb9b-1010ebea49b8.png)
> 
> Files look like this:
> 
> ![image](https://user-images.githubusercontent.com/23311037/211837832-23b218b1-05ba-449a-9b29-3888adcbec30.png)

Hi David,

If your input data is "One sample per file", PTI will automatically filter out mutations on heterochromosome according to the first item of "mut_id", and only mutations on Chr1-22 and X,Y will be retained. You can try to use the "chromosome_startPos_endPos_RefBase_AltBase" format to record mutations, as in the Demo file. 

If you don't want to filter out mutations on heterochromosome, an alternative is to modify the script “PTI.py”. You can change the command 
>>"if AF_data>=float(AF) and data[0].split('_')[0] in all_chr:" 
to 
>>"if AF_data>=float(AF):".

Please try running PTI again and feel free to ask if you have any questions.

Best,
wupin

**Comment by Dagsbio** [comment]
Thank you for the suggestion. It now works. 

I was now trying to make sense of the resulting plots. 

My input dataset consists of one parental cell line (in the bottom part, with a "wt") and a few derived resistant cell lines (pl1, 12, 1, 4 and 6):

![image](https://user-images.githubusercontent.com/23311037/212873438-60933c73-2bd4-4ef6-81df-fd0fa2d9b416.png)

Can I then say: the closest samples phylogenetically speaking are (starting from wt):  6 and 4, then 12 and 1 and finally pl1? 

What are the numbers in brakets and the numbers outside brakets?  Whats the meaning in the increase or decrease of units in both the X and Y axis? 

Finally, do yo think is there a way I can plot this without having overlapping characters so the sample names are well displayed? do you know if there's any other tool for plotting this type of data that I could use? Although this part I guess isn't crucial I would like to try to get some maybe coloured plots. 

Thank you for your time, help and quick responses.

David.

**Comment by Dagsbio** [comment]
By the way, When I tried to plot all the samples that I have (they are all carry a common mutation in EGFR) in order to get a single plot, I realized is a never ending job (or at least that what it looks). They are 19 samples:

![image](https://user-images.githubusercontent.com/23311037/212967913-56c42da0-6a2c-45eb-b985-0cebe143b180.png)

I tried reducing the number of mutations but it stays the same...any ideas?

Thank you again!

**Comment by Bio-wupin** [comment]
> 

Hi David,

Here are the answers to your questions. Hope can help you.

Q: Can I then say: the closest samples physiologically speaking are (starting from wt): 6 and 4, then 12 and 1 and finally pl1?
My answer: From the results of PTI, you can know the genetic distance between different samples. Samples that were clustered on the same branch shared more mutations, that is, they had more similar genetic variation. So your understanding is correct. It is also recommended that you pay attention to the output file "*_info_0.txt", which records information about mutations that occur on more than two branches.


Q: What are the numbers in brakes and the numbers outside brakes? Whats the meaning in the increase or decrease of units in both the X and Y axis?
My answer: The annotation information on the branches includes the length of the branches (outside brackets), which is equal to the number of shared mutations, and the number of mutated driver genes was also annotated in brackets. The X and Y axes only represent the canvas size, which can be ignored.

Q: do you know if there's any other tool for plotting this type of data that I could use?
My answer: You can try some tools or packages like ggtree, GraPhlAn, AnnoTree, etc.

Best,
wupin

**Comment by Bio-wupin** [comment]
> By the way, When I tried to plot all the samples that I have (they are all carry a common mutation in EGFR) in order to get a single plot, I realized is a never ending job (or at least that what it looks). They are 19 samples:
> 
> ![image](https://user-images.githubusercontent.com/23311037/212967913-56c42da0-6a2c-45eb-b985-0cebe143b180.png)
> 
> I tried reducing the number of mutations but it stays the same...any ideas?
> 
> Thank you again!

My guess is there are two reasons for the long running time of PTI: one is the large overall sample size, and the other is that there are too few mutations shared between samples, which will cause PTI to spend a lot of time searching for the optimal branch split. In the PTI manual, we also recommend that "The number of mutations used to reconstruct the phylogenetic tree has a significant impact on the accuracy of the tree structure. We recommend that the number of mutations used to build a tree for each tumor sample is no less than 30”.
